### ISSUE TITLE
mistake in hygfz

### ISSUE THREAD

**Issue by stla** [gajdosandrej/CharFunToolR#1]
Hello. In the `hygfz` function, the code shoud be

`zf0 <- zf0 + zr * g0 / gcbk`
instead of 

`zf0 < zf0 + zr * g0 / gcbk`

Line 440 of [this file] (https://github.com/gajdosandrej/CharFunToolR/blob/cdd673ee9e854f625a07bdf511673fdd30cb374d/R/Hypergeom2F1.R).

**Comment by gajdosandrej** [comment]
> Hello. In the `hygfz` function, the code shoud be
> 
> `zf0 <- zf0 + zr * g0 / gcbk`
> instead of
> 
> `zf0 < zf0 + zr * g0 / gcbk`
> 
> Line 440 of [this file] (https://github.com/gajdosandrej/CharFunToolR/blob/cdd673ee9e854f625a07bdf511673fdd30cb374d/R/Hypergeom2F1.R).

Hello. 
Thank you for your comment. It's fixed now.
